version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-syvora}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-syvora_pass}
      POSTGRES_DB: ${POSTGRES_DB:-syvoradb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-syvora}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-syvora}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-syvora_pass}
      - POSTGRES_DB=${POSTGRES_DB:-syvoradb}
      - APP_PORT=${APP_PORT:-3000}
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
