apiVersion: v1
kind: Service
metadata:
  name: {{ include "syvora-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "syvora-backend.name" . }}
    helm.sh/chart: {{ include "syvora-backend.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "syvora-backend.name" . }}
